export interface CityData {
    slug: string;
    name: string;
    displayName: string;
    heroSubtitle: string;
    intro: string;
    localDetail: string;
    neighborhoods: string;
    processNote: string;
    ctaText: string;
    faqCity: string; // para personalizar FAQs
}

export const cities: CityData[] = [
    {
        slug: "sant-cugat",
        name: "Sant Cugat del Vallès",
        displayName: "Sant Cugat",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>Sant Cugat del Vallès</strong>, una de las localidades con mayor nivel adquisitivo del área metropolitana de Barcelona. Conocemos a fondo las singularidades urbanísticas del municipio: desde las viviendas unifamiliares de <strong>Mira-sol, Volpelleres y Can Gatxet</strong> hasta los pisos de obra nueva y segunda mano del Eixample de Sant Cugat.`,
        localDetail: `Sant Cugat del Vallès combina el encanto de sus zonas históricas —con el entorno del Monestir Benedictí como referencia— con urbanizaciones residenciales de alto standing donde conviven jardines privados, piscinas y propiedades de más de 400m². En barrios como <strong>La Floresta, El Coll Favà o Can Bellet</strong>, la reforma integral es una inversión que revaloriza significativamente el inmueble. Gestionamos los permisos de obra ante el <strong>Ajuntament de Sant Cugat del Vallès</strong> y trabajamos habitualmente con las tipologías constructivas más comunes de la zona: masías rehabilitadas, chalets de los años 80 y apartamentos en el centro urbano.`,
        neighborhoods: "Mira-sol, Volpelleres, Can Gatxet, La Floresta, El Coll Favà, Can Bellet y el centro histórico",
        processNote: "Nuestro equipo se desplaza sin coste a cualquier punto de Sant Cugat del Vallès para la visita técnica previa.",
        ctaText: "Presupuesto de Reforma Integral en Sant Cugat",
        faqCity: "Sant Cugat del Vallès",
    },
    {
        slug: "badalona",
        name: "Badalona",
        displayName: "Badalona",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Badalona</strong>, tercera ciudad de Cataluña y uno de los municipios con mayor potencial de revalorización inmobiliaria del área metropolitana. La ciudad atesora un parque de viviendas muy heterogéneo que va desde bloques de los años 60 en plena transformación hasta pisos de nueva construcción junto al litoral.`,
        localDetail: `Trabajamos en todos los barrios de Badalona: <strong>La Salut, Bufalà, Artigas, Canyadó, Sant Joan de Badalona, Coll i Pujol y el Centre Urbà</strong>. En la franja costera, donde la demanda de vivienda premium ha crecido notablemente en los últimos años, ejecutamos reformas de alto standing con materiales de primera categoría. En los barrios de interior como <strong>Pomar o Morera</strong>, adaptamos el proyecto a los condicionantes estructurales de los edificios de más de 50 años de antigüedad, actualizando instalaciones eléctricas, fontanería y distribución interior. Tramitamos la documentación ante el <strong>Ajuntament de Badalona</strong>.`,
        neighborhoods: "La Salut, Bufalà, Artigas, Canyadó, Sant Joan, Coll i Pujol, Centre Urbà, Pomar y Morera",
        processNote: "Cubrimos toda Badalona con tiempo de respuesta inferior a 48 horas para la visita técnica inicial.",
        ctaText: "Presupuesto de Reforma Integral en Badalona",
        faqCity: "Badalona",
    },
    {
        slug: "santa-coloma",
        name: "Santa Coloma de Gramenet",
        displayName: "Santa Coloma de Gramenet",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> ejecutamos reformas integrales en <strong>Santa Coloma de Gramenet</strong>, municipio del Barcelonès que limita directamente con Barcelona y que concentra un elevado número de viviendas de entre 40 y 80 años de antigüedad con gran potencial de renovación. Nuestra experiencia en la zona nos permite anticipar los retos técnicos de la construcción característica de los años 60-80.`,
        localDetail: `En barrios como <strong>Singuerlín, Santa Rosa, Can Mariner, La Guinardera, Safaretjos, Riu Nord y Riu Sud</strong>, intervenimos en pisos que requieren una actualización integral: sustitución completa de tuberías y cableado eléctrico, apertura de espacios para lograr plantas diáfanas, instalación de sistemas de climatización eficientes y renovación total de baños y cocinas. El resultado es una vivienda que multiplica su valor y confort. Gestionamos todos los trámites con el <strong>Ajuntament de Santa Coloma de Gramenet</strong>, desde el 'Assabentat' hasta la Llicència d'Obres Majors.`,
        neighborhoods: "Singuerlín, Santa Rosa, Can Mariner, La Guinardera, Safaretjos, Riu Nord y Riu Sud",
        processNote: "Desplazamiento gratuito a cualquier punto de Santa Coloma de Gramenet para la visita técnica.",
        ctaText: "Presupuesto de Reforma Integral en Santa Coloma de Gramenet",
        faqCity: "Santa Coloma de Gramenet",
    },
    {
        slug: "sant-quirze",
        name: "Sant Quirze del Vallès",
        displayName: "Sant Quirze del Vallès",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>Sant Quirze del Vallès</strong>, municipio residencial del Vallès Occidental conocido por su calidad de vida y su parque de viviendas unifamiliares de alta categoría. La proximidad a Sabadell y al corredor industrial del Vallès convierte a Sant Quirze en uno de los destinos preferidos de familias que buscan amplitud y tranquilidad sin alejarse de Barcelona.`,
        localDetail: `Intervenimos habitualmente en urbanizaciones como <strong>Can Poggio, Cal Xammar y Can Bassa</strong>, donde predominan las casas de planta baja y primer piso con jardín y piscina. En este tipo de inmuebles, la reforma integral permite rediseñar completamente la distribución, integrar cocinas al espacio de vida y crear suites con vestidor y baño privado. También trabajamos en los bloques residenciales del centro urbano. Tramitamos la documentación necesaria ante el <strong>Ajuntament de Sant Quirze del Vallès</strong> con total garantía.`,
        neighborhoods: "Can Poggio, Cal Xammar, Can Bassa y el centro urbano de Sant Quirze",
        processNote: "Visita técnica gratuita en Sant Quirze del Vallès en menos de 48 horas.",
        ctaText: "Presupuesto de Reforma Integral en Sant Quirze del Vallès",
        faqCity: "Sant Quirze del Vallès",
    },
    {
        slug: "terrassa",
        name: "Terrassa",
        displayName: "Terrassa",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Terrassa</strong>, segunda ciudad del área metropolitana de Barcelona y capital del Vallès Occidental. Con una vasta experiencia en las diferentes tipologías constructivas de Terrassa —desde los edificios modernistas del centro histórico hasta los bloques residenciales de expansión— ofrecemos proyectos llave en mano adaptados a cada inmueble.`,
        localDetail: `Desarrollamos proyectos de reforma integral en todos los barrios de Terrassa: <strong>Centre, Eixample, Sant Pere Nord, Can Palet, Ca n'Anglada, Les Arenes, Montserrat, Vallparadís y Egara</strong>. La ciudad cuenta con un patrimonio arquitectónico modernista excepcional —la Masia Freixa, la Casa Alegre de Sagrera— que requiere especial sensibilidad en las intervenciones sobre fachadas y elementos protegidos. En los barrios de reciente construcción, nos centramos en maximizar la funcionalidad y la eficiencia energética. Gestionamos todos los permisos ante el <strong>Ajuntament de Terrassa</strong>.`,
        neighborhoods: "Centre, Eixample, Sant Pere Nord, Can Palet, Ca n'Anglada, Les Arenes, Montserrat, Vallparadís y Egara",
        processNote: "Equipo desplazado permanentemente en la comarca del Vallès Occidental para garantizar presencia ágil en Terrassa.",
        ctaText: "Presupuesto de Reforma Integral en Terrassa",
        faqCity: "Terrassa",
    },
    {
        slug: "hospitalet",
        name: "L'Hospitalet de Llobregat",
        displayName: "L'Hospitalet de Llobregat",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>L'Hospitalet de Llobregat</strong>, segunda ciudad más poblada de Cataluña y uno de los mercados inmobiliarios con mayor dinamismo del área metropolitana de Barcelona. La proximidad al centro de Barcelona, la mejora de la oferta cultural y la regeneración urbana hacen de l'Hospitalet un municipio de gran interés para la inversión inmobiliaria.`,
        localDetail: `Operamos en todos los distritos y barrios de l'Hospitalet: <strong>Centre, Collblanc, La Torrassa, Santa Eulàlia, Pubilla Cases, Bellvitge, Can Serra, Les Planes, El Gornal y Gran Via Sud</strong>. En zonas como Bellvitge, con grandes bloques residenciales de los años 70, la reforma integral supone una transformación radical del confort y la eficiencia energética de la vivienda. En el Centre i Collblanc, donde la demanda de alquiler y compraventa es muy alta, la reforma añade un valor económico directo al inmueble. Tramitamos los permisos ante el <strong>Ajuntament de l'Hospitalet de Llobregat</strong>.`,
        neighborhoods: "Centre, Collblanc, La Torrassa, Santa Eulàlia, Pubilla Cases, Bellvitge, Can Serra, Les Planes, El Gornal y Gran Via Sud",
        processNote: "Cubrimos toda la ciudad de L'Hospitalet con equipos propios, sin subcontratación.",
        ctaText: "Presupuesto de Reforma Integral en L'Hospitalet de Llobregat",
        faqCity: "L'Hospitalet de Llobregat",
    },
    {
        slug: "sant-just-desvern",
        name: "Sant Just Desvern",
        displayName: "Sant Just Desvern",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> ejecutamos reformas integrales en <strong>Sant Just Desvern</strong>, uno de los municipios con mayor renta per cápita de Cataluña y referente del urbanismo residencial de alta calidad en el área metropolitana de Barcelona. La exclusividad de este municipio, situado entre el Tibidabo y Esplugues, se refleja en el nivel de exigencia de sus propietarios.`,
        localDetail: `Trabajamos en todas las zonas de Sant Just Desvern: <strong>Can Biosca, El Palau, Els Molins, Cal Ros y el nucli urbà</strong>. Las viviendas unifamiliares de gran tamaño —muchas con parcelas superiores a 1.000m²— son el tipo de inmueble más habitual en nuestros proyectos. Aquí, la reforma integral va más allá de la simple renovación estética: diseñamos espacios que integran domótica, climatización por aerotermia, cocinas de alta gama y baños de spa, manteniendo o recuperando la arquitectura original del inmueble. Gestionamos los trámites con el <strong>Ajuntament de Sant Just Desvern</strong>.`,
        neighborhoods: "Can Biosca, El Palau, Els Molins, Cal Ros y el núcleo urbano",
        processNote: "Proyectos de alta gama con arquitecto técnico propio incluido en todos nuestros presupuestos en Sant Just Desvern.",
        ctaText: "Presupuesto de Reforma Integral en Sant Just Desvern",
        faqCity: "Sant Just Desvern",
    },
    {
        slug: "esplugues-de-llobregat",
        name: "Esplugues de Llobregat",
        displayName: "Esplugues de Llobregat",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Esplugues de Llobregat</strong>, municipio limítrofe con Barcelona, Cornellà y Sant Just Desvern que concentra una mezcla singular de zonas residenciales consolidadas y nuevas promociones de alta calidad. La posición estratégica de Esplugues, con excelentes conexiones al centro de Barcelona, lo convierte en uno de los mercados más activos del Baix Llobregat.`,
        localDetail: `Desarrollamos proyectos en todos los barrios de Esplugues: <strong>Can Vidalet, El Gornal, Esplugues Centre, Can Clos y La Miranda</strong>. En Can Vidalet y el Centro histórico abundan los bloques de los años 70 con gran potencial de mejora; en La Miranda y las zonas más elevadas encontramos viviendas unifamiliares de gran valor donde la reforma integral permite actualizar la imagen y las prestaciones sin perder el carácter arquitectónico del inmueble. Tramitamos toda la documentación con el <strong>Ajuntament d'Esplugues de Llobregat</strong>.`,
        neighborhoods: "Can Vidalet, El Gornal, Centre, Can Clos y La Miranda",
        processNote: "Equipo propio en el Baix Llobregat para respuesta inmediata en Esplugues de Llobregat.",
        ctaText: "Presupuesto de Reforma Integral en Esplugues de Llobregat",
        faqCity: "Esplugues de Llobregat",
    },
    {
        slug: "alella",
        name: "Alella",
        displayName: "Alella",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>Alella</strong>, encantador municipio del Maresme conocido por sus viñedos de la DO Alella y por ser una de las poblaciones con mayor concentración de propiedades de lujo y masías rehabilitadas de la comarca. La tranquilidad y el entorno natural de Alella atraen a familias que buscan calidad de vida a pocos minutos de Barcelona.`,
        localDetail: `En Alella realizamos reformas integrales en <strong>masías del siglo XVIII y XIX, viviendas unifamiliares en urbanizaciones como Can Teixidor o El Masnou conurbation, y pisos en el casco antiguo</strong>. La intervención sobre masías y edificios históricos requiere una sensibilidad especial para preservar elementos originales —bóvedas de cañón, vigas de madera, pavimentos hidráulicos— mientras se actualizan todas las instalaciones y se mejora la eficiencia energética. Tramitamos los permisos pertinentes con el <strong>Ajuntament d'Alella</strong> y contamos con experiencia en protección del patrimonio local.`,
        neighborhoods: "Casco antiguo, Can Teixidor y urbanizaciones residenciales de Alella",
        processNote: "Especializados en rehabilitación de masías y edificios históricos en el Maresme.",
        ctaText: "Presupuesto de Reforma Integral en Alella",
        faqCity: "Alella",
    },
    {
        slug: "cabrils",
        name: "Cabrils",
        displayName: "Cabrils",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> ejecutamos reformas integrales en <strong>Cabrils</strong>, pequeño municipio del Maresme de carácter residencial que comparte comarca con Vilassar de Mar y Cabrera de Mar. Cabrils es elegido por familias que valoran la tranquilidad del entorno rural, la proximidad al mar y las excelentes comunicaciones con Barcelona por la autopista C-32.`,
        localDetail: `En Cabrils las tipologías de vivienda predominantes son la <strong>casa unifamiliar con jardín</strong> —muchas construidas entre los años 80 y los 2000— y las masías tradicionales que buscan una segunda vida. En ambos casos, la reforma integral que realizamos contempla la renovación completa de instalaciones, la apertura de espacios interiores y la incorporación de soluciones de eficiencia energética como aerotermia y placas solares. Trabajamos en estrecha coordinación con el <strong>Ajuntament de Cabrils</strong> para la tramitación de licencias de obra.`,
        neighborhoods: "Núcleo urbano de Cabrils, urbanizaciones residenciales y masías del entorno",
        processNote: "Cobertura completa en el Maresme Nord con desplazamiento gratuito a Cabrils.",
        ctaText: "Presupuesto de Reforma Integral en Cabrils",
        faqCity: "Cabrils",
    },
    {
        slug: "tiana",
        name: "Tiana",
        displayName: "Tiana",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Tiana</strong>, exclusivo municipio de la ladera del Maresme que ofrece espectaculares vistas al Mediterráneo y un entorno natural incomparable a tan solo 20 minutos de Barcelona. Las propiedades en Tiana son codiciadas por su privacidad, sus amplias parcelas y la calidad de vida que proporciona el municipio.`,
        localDetail: `El parque de viviendas de Tiana está compuesto mayoritariamente por <strong>viviendas unifamiliares de dos o tres plantas, algunas con piscina y amplios jardines</strong>, edificadas a lo largo de las décadas de los 70, 80 y 90. La reforma integral en estas propiedades nos permite transformar distribuciones anticuadas en espacios abiertos y luminosos, renovar completamente los baños y cocinas, instalar sistemas de climatización eficientes y mejorar el aislamiento térmico y acústico. Tramitamos todos los permisos con el <strong>Ajuntament de Tiana</strong>.`,
        neighborhoods: "Nucli urbà de Tiana, les urbanitzacions de la ladera y els Turons de Tiana",
        processNote: "Especialistas en reformas integrales de viviendas unifamiliares en el Maresme.",
        ctaText: "Presupuesto de Reforma Integral en Tiana",
        faqCity: "Tiana",
    },
    {
        slug: "sitges",
        name: "Sitges",
        displayName: "Sitges",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>Sitges</strong>, uno de los destinos más exclusivos del litoral mediterráneo catalán y referente internacional del turismo de calidad. La demanda de propiedades reformadas en Sitges —tanto por parte de familias barcelonesas como de residentes internacionales— convierte la reforma integral en una inversión de alta rentabilidad.`,
        localDetail: `Operamos en todas las zonas de Sitges: el <strong>Centre Històric</strong> —con sus casas señoriales y casas d'indianes del siglo XIX—, las urbanizaciones residenciales de <strong>Terramar, Vallpineda, El Vinyet y Les Botigues de Sitges</strong>, y los apartamentos del frente marítimo. En el centro histórico, la intervención requiere cumplir con las normativas de protección del patrimonio arquitectónico; en Terramar y Vallpineda, las grandes villas de los años 60-80 encuentran en la reforma integral una oportunidad de alcanzar estándares de lujo contemporáneo. Gestionamos los permisos con el <strong>Ajuntament de Sitges</strong>.`,
        neighborhoods: "Centre Històric, Terramar, Vallpineda, El Vinyet, Les Botigues de Sitges y el frente marítimo",
        processNote: "Experiencia acreditada en reformas de casas señoriales y patrimonio arquitectónico en Sitges.",
        ctaText: "Presupuesto de Reforma Integral en Sitges",
        faqCity: "Sitges",
    },
    {
        slug: "castelldefels",
        name: "Castelldefels",
        displayName: "Castelldefels",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> ejecutamos reformas integrales en <strong>Castelldefels</strong>, municipio costero del Baix Llobregat que combina las ventajas del litoral mediterráneo con la proximidad al aeropuerto de Barcelona-El Prat y una excelente conexión en tren con el centro de la ciudad. La alta concentración de segunda residencia y la llegada continua de familias internacionales hacen de Castelldefels un mercado muy activo para la reforma residencial.`,
        localDetail: `Desarrollamos proyectos de reforma integral en todas las zonas de Castelldefels: la <strong>Platja de Castelldefels</strong> —con sus villas y apartamentos con vistas al mar—, el <strong>Centre i el nucli original</strong>, la <strong>urbanització de Bellamar</strong> con sus casas unifamiliares, y los nuevos desarrollos residenciales de <strong>Can Bou y El Castell</strong>. En la zona de playa, adaptamos las viviendas a las exigencias de la vida costera: materiales resistentes a la humedad y la sal, ventanas de altas prestaciones y sistemas de climatización de última generación. Tramitamos los permisos con el <strong>Ajuntament de Castelldefels</strong>.`,
        neighborhoods: "Platja de Castelldefels, Centre, Bellamar, Can Bou y El Castell",
        processNote: "Especializados en reformas de viviendas de costa y segunda residencia en el Baix Llobregat.",
        ctaText: "Presupuesto de Reforma Integral en Castelldefels",
        faqCity: "Castelldefels",
    },
    {
        slug: "teia",
        name: "Teià",
        displayName: "Teià",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Teià</strong>, tranquilo municipio del Maresme situado entre Alella y El Masnou que ha consolidado su posición como uno de los municipios más exclusivos de la comarca. Su paisaje de viñedos, su carácter rural y la proximidad al mar hacen de Teià el lugar ideal para quienes buscan residencia de alta calidad con fácil acceso a Barcelona.`,
        localDetail: `En Teià trabajamos principalmente en <strong>masías rehabilitadas, viviendas unifamiliares de gran tamaño y propiedades con amplio terreno</strong>. La reforma integral en estas propiedades suele incluir la rehabilitación de elementos constructivos originales —muros de piedra, arcos, bóvedas—, la actualización completa de las instalaciones y la incorporación de sistemas de eficiencia energética como aerotermia y placas fotovoltaicas. También ejecutamos proyectos en los pisos del nucli urbà. Coordinamos la tramitación de permisos con el <strong>Ajuntament de Teià</strong>.`,
        neighborhoods: "Nucli urbà de Teià, masías del entorno y urbanizaciones residenciales",
        processNote: "Especializados en rehabilitación de masías y propiedades históricas en el Maresme.",
        ctaText: "Presupuesto de Reforma Integral en Teià",
        faqCity: "Teià",
    },
    {
        slug: "sant-vicenc-de-montalt",
        name: "Sant Vicenç de Montalt",
        displayName: "Sant Vicenç de Montalt",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> somos especialistas en reformas integrales en <strong>Sant Vicenç de Montalt</strong>, encantador municipio costero del Maresme conocido por sus urbanizaciones residenciales de alto nivel y su playa tranquila. La ubicación de Sant Vicenç, entre el mar y las colinas del Maresme, y la cercanía a Sant Andreu de Llavaneres, lo convierten en destino preferido de familias que buscan exclusividad y calidad de vida.`,
        localDetail: `Intervenimos en las <strong>urbanizaciones residenciales de Sant Vicenç de Montalt</strong>, donde predominan las viviendas unifamiliares de los años 80 y 90 con jardín y piscina, así como en los pisos del nucli urbà y las propiedades próximas a la playa. En este tipo de inmuebles, la reforma integral que ejecutamos contempla la renovación total de baños y cocinas, la apertura de espacios, la mejora del aislamiento y la instalación de sistemas de climatización eficientes. Tramitamos la documentación necesaria con el <strong>Ajuntament de Sant Vicenç de Montalt</strong>.`,
        neighborhoods: "Nucli urbà, urbanizaciones residenciales, zona de playa y el entorno de la serra del Maresme",
        processNote: "Cobertura completa en el Maresme con visita técnica gratuita en Sant Vicenç de Montalt.",
        ctaText: "Presupuesto de Reforma Integral en Sant Vicenç de Montalt",
        faqCity: "Sant Vicenç de Montalt",
    },
    {
        slug: "vilassar-de-dalt",
        name: "Vilassar de Dalt",
        displayName: "Vilassar de Dalt",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> ejecutamos reformas integrales en <strong>Vilassar de Dalt</strong>, pintoresco municipio interior del Maresme con un casco histórico medieval muy bien conservado y una creciente comunidad de familias que han elegido este municipio por su calidad de vida, su entorno natural y su carácter auténticamente catalán, diferenciándose de su municipio hermano Vilassar de Mar en el litoral.`,
        localDetail: `Trabajamos tanto en el <strong>nucli medieval de Vilassar de Dalt</strong> —con sus casas de arquitectura tradicional catalana, piedra vista y pavimentos históricos— como en las <strong>urbanizaciones residenciales del entorno</strong> y las masías de la zona agrícola del municipio. La reforma integral en el casco histórico requiere especial cuidado con los elementos patrimoniales y la coordinación con el Servei de Patrimoni. En las viviendas unifamiliares modernas, el enfoque es la eficiencia energética y el confort. Tramitamos permisos con el <strong>Ajuntament de Vilassar de Dalt</strong>.`,
        neighborhoods: "Nucli medieval, urbanizaciones residenciales, Can Nadal y las masías del término municipal",
        processNote: "Experiencia en rehabilitación de edificios en cascos históricos del Maresme.",
        ctaText: "Presupuesto de Reforma Integral en Vilassar de Dalt",
        faqCity: "Vilassar de Dalt",
    },
    {
        slug: "matadepera",
        name: "Matadepera",
        displayName: "Matadepera",
        heroSubtitle: "Diseño, Arquitectura y Ejecución Llave en Mano",
        intro: `En <strong>Voltura Projects</strong> realizamos reformas integrales en <strong>Matadepera</strong>, uno de los municipios con mayor renta per cápita de Cataluña y referente del urbanismo residencial de lujo en el Vallès Occidental. Situado al pie del Parc Natural de Sant Llorenç del Munt i l'Obac y a escasos minutos de Terrassa, Matadepera es el destino escogido por quienes buscan lo mejor del mundo rural y el máximo nivel de vida.`,
        localDetail: `El tejido residencial de Matadepera está dominado por <strong>viviendas unifamiliares de gran tamaño, masías rehabilitadas y propiedades con amplísimos jardines y piscina</strong>. En este contexto de alta exigencia, nuestros proyectos de reforma integral contemplan la integración de tecnología domótica, sistemas de aerotermia y fotovoltaica, cocinas de alta gama de diseño, baños tipo spa y espacios de trabajo en el propio hogar. Mantenemos una fluida relación con el <strong>Ajuntament de Matadepera</strong> para la tramitación eficiente de todas las licencias de obra.`,
        neighborhoods: "El nucli urbà de Matadepera, urbanizaciones residenciales de alta gama y masías del Parc de Sant Llorenç",
        processNote: "Proyectos de reforma de alta gama con arquitecto técnico propio en Matadepera.",
        ctaText: "Presupuesto de Reforma Integral en Matadepera",
        faqCity: "Matadepera",
    },
];

export function getCityBySlug(slug: string): CityData | undefined {
    return cities.find((c) => c.slug === slug);
}
